sonar.projectKey=sigc-gas
sonar.projectName=SIGC-GAS

sonar.host.url=http://localhost:9000

sonar.sources=backend/src,frontend/src

sonar.exclusions=backend/src/scripts/**,backend/src/**/*.test.js,frontend/src/**/*.test.js

sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info